# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to gh pages branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3
    - name: Git login
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "gh-actions"
        echo "machine github.com login git password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
    - run: yarn install
    # - run: npm run build --if-present
    - env:
        GIT_USER: git
      run: npm run deploy
